name: propel
channels:
  - conda-forge
  - anaconda
  - plotly
dependencies:
  - python=3.10
  - pip=23.2
  - pip:
    - graphviz==0.20.1
    - imbalanced_learn==0.11.0
    - lightgbm==3.3.5
    - matplotlib==3.8.2
    - numba==0.56.4
    - numpy==1.22.4
    - pandas==2.1.4
    - scikit_learn==1.3.2
    - seaborn==0.13.1
    - shap==0.44.0
    - sweetviz==2.1.4
    - wandb==0.16.1
    - xgboost==2.0.3
